### PR TITLE
looksee currently does not support anything above 2.2

### PR DESCRIPTION
**Pull request by mathieujobin**

### CODE REVIEW

**Comment by mathieujobin** [comment]
not sure the message is actually much clearer...

```
Could not find gem 'looksee' in source at `../../opensource/looksee`.
Source contains 'looksee' at: 3.1.0 ruby
```

also, this won't prevent you from making a condition if your run your app against multiple rubies.

what I do, is 

`gem 'looksee' if RUBY_VERSION < '2.3.0'`

**Comment by josephks** [comment]
I think it is better that bundler doesn't find a gem than bundler tries to install the gem and the borrower gets a compile error.  Also if you do this to the gemspec the rubygems.org page will have the requirement right there so users know what the issue is right then without having to go to github and explore the open issues.

**Comment by mathieujobin** [comment]
@josephks agreed ! i just wish it would say something else, but i guess that's a fix we should submit to `bundler`

**Comment by mathieujobin** [comment]
the travis build will pass if you merge https://github.com/oggy/looksee/pull/37/files first

**Comment by mathieujobin** [comment]
@oggy this should be good to merge !

**Comment by oggy** [comment]
Thanks for that -- pushed!

**Pull request merged**
