### PR TITLE
Ruby 3.0 Support

### LINKED ISSUE #54: Support for Ruby 3
Requesting support for Ruby 3.

Thanks.

### PR DESCRIPTION
**Pull request by mathieujobin**
closes #54

### CODE REVIEW

**Comment by mathieujobin** [comment]
I don't know why the Travis status doesn't show up
but it builds and all test passes

https://travis-ci.com/github/mathieujobin/looksee/builds/212586931

**Comment by mathieujobin** [comment]
Tested!

```
$ bundle 
Fetching git@github.com:mathieujobin/looksee
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 2.2.3
Using looksee 4.3.0 from git@github.com:mathieujobin/looksee (at ruby-3.0@f39c4e9)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle exec irb
3.0.0 :001 > RUBY_VERSION
 => "3.0.0" 
3.0.0 :002 > RUBY_VERSION.ls
/home/mathieu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/bundler/gems/looksee-f39c4e9c22cd/lib/looksee/adapter/base.rb:58: warning: Looksee cannot display undef-ed methods on MRI 2.3 or later
 => 
BasicObject
  !       __send__       instance_exec             singleton_method_undefined
  !=      equal?         method_missing          
  ==      initialize     singleton_method_added  
  __id__  instance_eval  singleton_method_removed
Kernel
...
```

**Comment by mathieujobin** [comment]
until this is merged, you can use like this

```
prj$ cat Gemfile
source 'https://rubygems.org'

ruby '3.0'

gem 'looksee', git: 'git@github.com:mathieujobin/looksee', branch: 'ruby-3.0'
```

**Comment by oggy** [comment]
Thanks for jumping on this @mathieujobin!

Merged & released 4.4.0.

**Comment by mathieujobin** [comment]
@oggy curious why you don't use Github to merge the PR ? 

it shows as Closed instead of Merged?

**Pull request closed without merging**
